web/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token
from api.views import image_views, views, account_verify_view, camera_shutter_view,number_plate_view
# from api import views


router = routers.DefaultRouter()
router.register(r'images', views.UploadedImagesViewSet, r'images')
router.register(r'employee', views.EmployeeViewSet, 'employee_info')
router.register(r'group', views.GroupViewSet)
# 店舗情報を取得
router.register(r'store/info', views.StoreViewSet)
router.register(r'employee/info', views.EmployeeViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),

    # 画像アップロード,削除
    url(r'^image/$', image_views.image_view),

    # シャッター
    url(r'^shutter',camera_shutter_view.camera_shutter),

    # 店舗トークン作成
    url(r'^store/createtoken',account_verify_view.store_create_token),
    # 従業員トークン作成
    url(r'^employee/createtoken', account_verify_view.employee_create_token),

    url(r'^store/verifytoken', account_verify_view.store_verify_token),
    url(r'^employee/verifytoken',account_verify_view.employee_verify_token),

    url(r'^revocationtoken',account_verify_view.revocation_token),

    # ナンバープレート登録
    url(r'^numberplate',number_plate_view.register_number_plate)

]

web/sotsusei-server-app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
import os, re
from django.shortcuts import redirect
# from api.urls import router as api_router

ApiVersion = 'v1/'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^api/' + ApiVersion, include(api_router.urls)),
    url(r'^api/' + ApiVersion, include('api.urls')),
    url(r'^web/', include('web.urls',namespace='web')),
    # url(r'',lambda request: redirect("/admin/")), # adminへのリダイレクト処理
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

path = os.path.expanduser('~/sotsusei') + '/'

web/web/urls.py
from django.conf.urls import url, static
from django.contrib.auth import views as auth_views
from . import views
# from django.contrib.auth import views as auth_views

app_name = 'web'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    # url(r'^image/$', views.image, name='image'),
    url(r'^image/$', views.image_new, name='image'),
    # url(r'^board/$', views.board, name='board'),
    url(r'^blacklist/$', views.blacklist, name='blacklist'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^ihochusha/$', views.parking, name='parking'),

    url(r'^mypage/$', views.mypage, name='mypage'),
    url(r'^redirect/$', views.redilect, name='redirect'),
    url(r'^login_sid/$', views.login_home_sid, name='login_home_sid'),
    url(r'^login_eid/$', views.login_home_eid, name='login_home_eid'),
    url(r'^login_auth_store/$', views.login_auth_store, name='login_auth_store'),
    url(r'^login_auth_employee/$', views.login_auth_employee, name='login_auth_employee'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^', views.home, name='other'),
]

web/templates/base.html
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock %} - watch</title>
    {% block style %}{% endblock %}
    <link rel="stylesheet" href="{% static 'web/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'web/bulma/css/bulma.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/main.css' %}" />
    <script src="{% static 'web/js/jquery-3.3.1.min.js' %}"></script>
{#    <script src="{% static 'web/js/lazyload.min.js' %}"></script>#}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
</head>
<body>
<nav class="navbar has-shadow is-fixed-top">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'web:home' %}">
                <img src="/static/web/img/watch.png" alt="watch">
            </a>

            <div class="navbar-burger burger" data-target="navMenu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div id="navMenu" class="navbar-menu">

            <div class="navbar-menu is-active">
                <div class="navbar-end">
                    <a class="navbar-item is-hidden-desktop {% block navbr_home_active %}{% endblock %}" href="{% url 'web:home' %}"> <i class="fa fa-home"></i>
                        ホーム
                    </a>
                    <a class="navbar-item is-hidden-desktop {% block navbr_image_active %}{% endblock %}" href="{% url 'web:image' %}"><i class="fa fa-file-image-o"></i>
                        画像一覧
                    </a>
                    <a class="navbar-item  is-hidden-desktop {% block navbr_parking_active %}{% endblock %}" href="{% url 'web:parking' %}"><i class="fa fa-car"></i>
                        違法駐車
                    </a>
                    <a class="navbar-item is-hidden-desktop {% block navbr_blacklist_active %}{% endblock %}" href="{% url 'web:blacklist' %}"><i class="fa fa-list"></i>
                        ブラックリスト
                    </a>
                    <a class="navbar-item is-hidden-desktop {% block navbr_setting_active %}{% endblock %}" href="{% url 'web:setting' %}"><i class="fa fa-gear"></i>
                        設定
                    </a>

                    <hr class="navbar-divider is-hidden-desktop" >
                    <a class="navbar-item" href="{% url 'web:logout' %}"><i class="fa fa-sign-out"></i>
                        ログアウト
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>

<html class="has-navbar-fixed-top">
<section class="main-content columns is-fullheight has-navbar-fixed-top">

    <aside class="column is-2 aside hero is-fullheight is-hidden-touch">
        <div>
            <div class="main">
                <a href="{% url 'web:home' %}" class="item {% block nav_home_active %}{% endblock %}"><span class="icon"><i class="fa fa-home"></i></span><span
                        class="name">ホーム</span></a>
                <a href="{% url 'web:image' %}" class="item {% block nav_image_active %}{% endblock %}"><span class="icon"><i class="fa fa-file-image-o"></i></span><span
                        class="name">画像一覧</span></a>
                <a href="{% url 'web:parking' %}" class="item {% block nav_parking_active %}{% endblock %}"><span class="icon"><i class="fa fa-car"></i></span><span
                        class="name">違法駐車</span></a>
                <a href="{% url 'web:blacklist' %}" class="item {% block nav_blacklist_active %}{% endblock %}"><span class="icon"><i class="fa fa-list"></i></span><span
                        class="name">ブラックリスト</span></a>
                <a href="{% url 'web:setting' %}" class="item {% block nav_setting_active %}{% endblock %}"><span class="icon"><i class="fa fa-gear"></i></span><span
                        class="name">設定</span></a>
            </div>
        </div>
    </aside>

    <div class="container column is-10">
        <div class="section">
            {% block contents %}{% endblock %}
        </div>
    </div>

</section>

<footer class="footer">
    <div class="container">
        <div class="content has-text-centered">
            <p>© 卒業制作2018 防犯野郎Aチーム</p>
        </div>
    </div>
</footer>

</html>
{% block end_scripts %}{% endblock %}
<script src="{% static 'web/bulma/js/clipboard-1.7.1.min.js' %}"></script>
<script src="{% static 'web/bulma/js/main.js' %}"></script>
<script src="{% static 'web/js/jquery.lazyload.min.js' %}"></script>

<script type="text/javascript" charset="utf-8">
    $("img.lazy").lazyload();
</script>
</body>
</html>