web/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token
from api.views import image_views, views, account_verify_view, camera_shutter_view,number_plate_view
# from api import views


router = routers.DefaultRouter()
router.register(r'images', views.UploadedImagesViewSet, r'images')
router.register(r'employee', views.EmployeeViewSet, 'employee_info')
router.register(r'group', views.GroupViewSet)
# 店舗情報を取得
router.register(r'store/info', views.StoreViewSet)
router.register(r'employee/info', views.EmployeeViewSet)

app_name = 'api'
urlpatterns = [
    url(r'^', include(router.urls)),

    # 画像アップロード,削除
    url(r'^image/$', image_views.image_view),

    # シャッター
    url(r'^shutter',camera_shutter_view.camera_shutter),

    # 店舗トークン作成
    url(r'^store/createtoken',account_verify_view.store_create_token),
    # 従業員トークン作成
    url(r'^employee/createtoken', account_verify_view.employee_create_token),

    url(r'^store/verifytoken', account_verify_view.store_verify_token),
    url(r'^employee/verifytoken',account_verify_view.employee_verify_token),

    url(r'^revocationtoken',account_verify_view.revocation_token),

    # ナンバープレート登録
    url(r'^numberplate',number_plate_view.register_number_plate)

]

web/sotsusei-server-app/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
import os, re
from django.shortcuts import redirect
# from api.urls import router as api_router

ApiVersion = 'v1/'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^api/' + ApiVersion, include(api_router.urls)),
    url(r'^api/' + ApiVersion, include('api.urls')),
    url(r'^web/', include('web.urls',namespace='web')),
    # url(r'',lambda request: redirect("/admin/")), # adminへのリダイレクト処理
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

path = os.path.expanduser('~/sotsusei') + '/'

web/web/urls.py
from django.conf.urls import url, static
from django.contrib.auth import views as auth_views
from . import views
# from django.contrib.auth import views as auth_views

app_name = 'web'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    # url(r'^image/$', views.image, name='image'),
    url(r'^image/$', views.image_new, name='image'),
    # url(r'^board/$', views.board, name='board'),
    url(r'^blacklist/$', views.blacklist, name='blacklist'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^ihochusha/$', views.parking, name='parking'),

    url(r'^mypage/$', views.mypage, name='mypage'),
    url(r'^redirect/$', views.redilect, name='redirect'),
    url(r'^login_sid/$', views.login_home_sid, name='login_home_sid'),
    url(r'^login_eid/$', views.login_home_eid, name='login_home_eid'),
    url(r'^login_auth_store/$', views.login_auth_store, name='login_auth_store'),
    url(r'^login_auth_employee/$', views.login_auth_employee, name='login_auth_employee'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^', views.home, name='other'),
]

web/web/templates/web/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>bulma</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.1/css/bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.1.2/css/bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"> -->
    <!-- 記述場所⑤ -->
  </head>
  <body>
    <header class="navbar">
        <div class="navbar-start">
            <span class="navbar-item">
                <a class="fa fa-language" href="home_bulma.html">HOME</a>
            </span>
        </div>
        <div class="navbar-end">
            <span class="navbar-item">
                <a class="fa fa-user" href="#">ログイン</a>
            </span>
        </div>
        <!-- 記述場所③ -->
    </header>
    <!-- 記述場所③ -->
    <main class="columns">
        <div class="submenu column is-2" style="margin-top: 10px;">
            <aside class="box menu">
                <ul class="menu-list">
                    <li><a href="home_bulma.html" class="is-active">HOME</a></li>
                    <li><a href="image_bulma.html">画像一覧</a></li>
                    <!-- <li><a href="board_bulma.html">掲示板</a></li> -->
                    <li><a href="parking_bulma.html">違法駐車</a></li>
                    <li><a href="blacklist_bulma.html">ブラックリスト</a></li>
                    <li><a href="configuration_bulma.html">設定</a></li>
                </ul>
            </aside>
        </div>

    </main>

  </body>
</html>

web/web/templates/web/blacklist_bulma.html
{% extends "base.html" %}
{% block title %}
    ブラックリスト
{% endblock title %}
{% block nav_blacklist_active %}
    active
{% endblock nav_blacklist_active %}
{% block navbar_blacklist_active %}
    is-active
{% endblock navbar_blacklist_active %}
{% block contents %}

    <div style="margin-top: 20px;">

        <div class="columns is-multiline">

            {% for data in dataList %}
                <div class="column is-2-widescreen is-3-desktop is-4-tablet">
                    <article class="box media image image is-square">
                        <a class="modal-button" data-target="modal-reg-{{ data.filename }}">
                            {#                            <img src="{{ data.first }}">#}
                            <img class="lazy" data-original="{{ data.first }}" style="padding-bottom: 50px;"/>
                        </a>
                        <p class="subtitle is-5">{{ data.humanname }}</p>
                    </article>

                    <div id="modal-reg-{{ data.filename }}" class="modal">
                        <div class="modal-background"></div>
                        <div class="modal-card">
                            <header class="modal-card-head">
                                <p class="modal-card-title">登録名：{{ data.humanname }}</p>
                                <button class="delete" aria-label="close"></button>
                            </header>
                            <section class="modal-card-body" style="overflow-y: scroll">
                                <div class="columns is-multiline">
                                    {% for onazi in data.all %}
                                        <div class="column is-4">
                                            <article class="box media image image is-square">
                                                <img src="{{ onazi }}"/>
                                            </article>
                                        </div>
                                    {% endfor %}
                                </div>
                            </section>
                            <footer class="modal-card-foot">
                                <form method='post' action=''>
                                    {% csrf_token %}
                                    <input type="hidden" name="blacklist_humanid" value="{{ data.humanid }}">
                                    <button class="button is-info">ブラックリスト登録を解除する</button>
                                </form>
                                <button class="button" style='margin-left: 20px;margin-bottom: 1em;'>閉じる</button>
                            </footer>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock contents %}

web/web/templates/web/dioalog_bulma.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>bulma</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.1.2/css/bulma.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <!-- 記述場所⑤ -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->
  </head>
  <body>
    <!-- 記述場所③ -->
    <main class="columns">
        
        <div class="column" style="margin-top: 10px;">
            <p><input type="button" value="削除" onClick="del()"></p>
            <p><input type="button" value="ログアウト" onClick="logout()"></p>
        </div>

    </main>
    <!-- 記述場所④ -->

    
    <script>

        // import swal from 'sweetalert';

        // swal("削除しますか？");
        
        function del(){
            // 「OK」時の処理開始 ＋ 確認ダイアログの表示
            if (window.confirm('本当に削除しますか？')) {

                location.href = "home_bulma.html"; // home_bulma.htmlへジャンプ

            }
            // 「OK」時の処理終了

            // 「キャンセル」時の処理開始
            else {

                window.alert('キャンセルされました'); // 警告ダイアログを表示

            }
            // 「キャンセル」時の処理終了
        }

        function logout() {
            
            // 「OK」時の処理開始 ＋ 確認ダイアログの表示
            if (window.confirm('本当にログアウトしますか？')) {

                location.href = "home_bulma.html"; // home_bulma.htmlへジャンプ

            }
            // 「OK」時の処理終了

            // 「キャンセル」時の処理開始
            else {

                window.alert('キャンセルされました'); // 警告ダイアログを表示

            }
            // 「キャンセル」時の処理終了

        }
    </script>
  </body>
</html>

web/web/templates/web/employee_login.html
{% load staticfiles %}
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <title>従業員ログイン</title>
    <link rel="stylesheet" href="{% static 'web/bulma/css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'web/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/default.css' %}">
</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-1 p-b-90">
            <form id="loginForm" class="login100-form validate-form flex-sb flex-w"
                  action="{% url 'web:login_auth_employee' %}" method="post">
                {% csrf_token %}
                <span class="login100-form-title p-b-51">
                        <img src="{% static 'web/img/watch.png' %}" style="width: 200px;"><br>
						従業員ログイン
					</span>


                <div class="wrap-input100 validate-input m-b-16" data-validate="Username is required">
                    <input class="input100" type="text" name="eid" placeholder="Employee ID" value="11111">
                </div>


                <div class="wrap-input100 validate-input m-b-16" data-validate="Password is required">
                    <input class="input100" type="password" name="epass" placeholder="Employee Pass" value="11111">
                </div>

                <div class="container-login100-form-btn m-t-17">
                    <button class="login100-form-btn">
                        ログイン
                    </button>
                </div>

                <a  class="modal-button login1000-form-create-store m-t-25" data-target="modal-reg">
                    従業員アカウントを作成
                </a>

                <a href="{% url 'web:logout' %}" class="login1000-form-create-store m-t-25">
                    店舗アカウントをログアウト
                </a>
            </form>

            <div id="modal-reg" class="modal">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title" align="center"> 従業員アカウントを作成</p>
                        <button class="delete" aria-label="close"></button>
                    </header>

                    <form method='post' action=''>
                        {% csrf_token %}
                        <input type="hidden" name="parking_add" value="parking_add">
                        <section class="modal-card-body">
                            <div class="Location">
                                <label class="label">従業員ID</label>
                                <div class="control">
                                    <input class="input" type="text" name="location">
                                </div>
                            </div>
                            <div class="Classnumber">
                                <label class="label">従業員名</label>
                                <div class="control">
                                    <input class="input" type="text" name="classnumber">
                                </div>
                            </div>
                            <div class="Location">
                                <label class="label">従業員パスワード</label>
                                <div class="control">
                                    <input class="input" type="text" name="location">
                                </div>
                            </div>
                            <div class="Hiragana">
                                <label class="label">グループID</label>
                                <div class="control">
                                    <input class="input" type="text" name="hiragana">
                                </div>
                            </div>
                            <div class="Location">
                                <label class="label">グループパスワード</label>
                                <div class="control">
                                    <input class="input" type="text" name="location">
                                </div>
                            </div>
                            <div class="Hiragana">
                                <label class="label">店舗の管理者ID</label>
                                <div class="control">
                                    <input class="input" type="text" name="hiragana">
                                </div>
                            </div>
                            <div class="Location">
                                <label class="label">店舗の管理者パスワード</label>
                                <div class="control">
                                    <input class="input" type="text" name="location">
                                </div>
                            </div>
                            <br>
                            グループID、グループパスワード または 店舗の管理者ID、店舗の管理者パスワードのどちらかが必要です。
                        </section>
                        <footer class="modal-card-foot">
                            <!-- <a class="modal-button" data-target="modal-reg2"><button class="button is-info">次へ</button></a> -->
                            <a class="modal-button">
                                <button class="button is-info">登録</button>
                            </a>
                            <a class="modal-button">
                                <button class="button" style="margin-left: 20px;">キャンセル</button>
                            </a>
                        </footer>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'web/bulma/js/clipboard-1.7.1.min.js' %}"></script>
<script src="{% static 'web/bulma/js/main.js' %}"></script>
<script src="{% static 'web/js/jquery.lazyload.min.js' %}"></script>
</body>
</html>

web/web/templates/web/home_bulma.html
{% extends "base.html" %}
{% block title %}
    ホーム
{% endblock title %}
{% block nav_home_active %}
    active
{% endblock nav_home_active %}
{% block navbr_home_active %}
    is-active
{% endblock navbr_home_active %}
{% block contents %}
    <div class="columns">
        <div class="column is-12">
            <article class="box media" style="height: 500px; overflow-y: scroll; margin-top: 10px;">
                <div class="media-content">
                    <div class="hero is-light">
                        <div class="hero-body">
                            <div class="container" style="width: 100%;">
                                <h1 class="title" align="center">カメライベント</h1>
                            </div>
                        </div>
                    </div>

                    {% if news_ary|length > 0 %}
                        {% for news in news_ary%}
                            <article class="media">
                                <a class="subtitle is-5" href="{% url 'web:image' %}">{{news.datetime}}　{{news.comment}}</a>
                            </article>
                        {% endfor %}
                    {% else %}
                        <p class="subtitle is-5 home-no-news-center">新着情報がありません</p>
                    {% endif %}
                </div>
            </article>
        </div>
    </div>
    <div class="columns">
        <div class="column is-6">
            <article class="box media" style="height: 500px;overflow-y: scroll;">
                <div class="media-content">

                    <div class="hero is-dark">
                        <div class="hero-body">
                            <div class="container" style="width: 100%">
                                <h1 class="title" align="center">違法駐車</h1>
                            </div>
                        </div>
                    </div>
                    {% if news_ihouchusha_ary|length > 0 %}
                        {% for news_ihouchusha in news_ihouchusha_ary %}
                            <article class="media">
                                <a class="subtitle is-5" href="{% url 'web:parking' %}">{{news_ihouchusha.datetime}}　{{news_ihouchusha.comment}}</a>
                            </article>
                        {% endfor %}
                    {% else %}
                        <p class="subtitle is-5 home-no-news-center">新着情報がありません</p>
                    {% endif %}

                </div>
            </article>
        </div>
        <div class="column is-6">
            <article class="box media" style="height: 500px; overflow-y: scroll;">
                <div class="media-content">

                    <div class="hero is-dark">
                        <div class="hero-body">
                            <div class="container" style="width: 100%;">
                                <h1 class="title" align="center">ブラックリスト</h1>
                            </div>
                        </div>
                    </div>
                    {% if news_blacklist_ary|length > 0 %}
                        {% for news_blacklist in news_blacklist_ary %}
                            <article class="media">
                                <a class="subtitle is-5" href="{% url 'web:blacklist' %}">{{news_blacklist.datetime}}　{{news_blacklist.comment}}</a>
                            </article>
                        {% endfor %}
                    {% else %}
                        <p class="subtitle is-5 home-no-news-center">新着情報がありません</p>
                    {% endif %}

                </div>
            </article>
        </div>
    </div>

{% endblock contents %}

web/web/templates/web/login_bulma.html
<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>従業員ログイン</title>
</head>

<body>
    <div align="center">
        <h1>従業員ログイン</h1>
        <table border="0">
            <!-- <form method='post' action='{% url 'web:login' %}'> -->
            <form action="home_bulma.html" method="post">
                <!-- {% csrf_token %} -->
                <tr>
                    <th>
                        Employee Login
                    </th>
                </tr>
                <tr>
                    <th>
                        <div id="emp_id"><input type="text" name="emp_id" placeholder="Employee ID" size="24"></div>
                        <div id="emp_pass"><input type="text" name="emp_pass" placeholder="Employee Passward" size="24"></div>
                    </th>
                </tr>
                <tr>
                    <th>
                        <div hidden id="next"><input type="button" value="次へ" size="24"></div>
                        <div id="Login"><input type="submit" value="Login" size="24"></div>
                    </th>
                </tr>
            </form>
        </table>
    </div>

    <script type="text/javascript">

        // $(function(){

        //     $('#next').click(function(){
        //         $('#pass').hide();
        //     });

        // });

    </script>


</body>

</html>

web/web/templates/web/sidemenu.html
<div class="submenu column is-2" style="margin-top: 10px;">
    <aside class="box menu">
        <ul class="menu-list">
            <li>
                <a href="../" {%if location_home %}class="is-active"{% endif %}>HOME</a>
            </li>
            <li>
                <a href="../image" {%if location_image %}class="is-active"{% endif %}>画像一覧</a>
            </li>
            <li>
                <a href="../ihochusha" {%if location_parking %}class="is-active"{% endif %}>違法駐車</a>
            </li>
            <li>
                <a href="../blacklist" {%if location_bl %}class="is-active"{% endif %}>ブラックリスト</a>
            </li>
            <li>
                <a href="../setting" {%if location_setting %}class="is-active"{% endif %}>設定</a>
            </li>
        </ul>
    </aside>
</div>

web/web/templates/web/store_login.html
{% load staticfiles %}
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <title>店舗ログイン</title>
    <link rel="stylesheet" href="{% static 'web/bulma/css/bulma.css' %}">
    <link rel="stylesheet" href="{% static 'web/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'web/css/default.css' %}">


</head>
<body>
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-1 p-b-90">
            <form id="loginForm" class="login100-form validate-form flex-sb flex-w" action="{% url 'web:login_auth_store' %}" method="post" >
                {% csrf_token %}
					<span class="login100-form-title p-b-51">
                        <img src="{% static 'web/img/watch.png' %}" style="width: 200px;"><br>
						店舗ログイン
					</span>


                <div class="wrap-input100 validate-input m-b-16" data-validate="Username is required">
                    <input class="input100" type="text" name="sid" placeholder="Store ID" value="00000">
                </div>


                <div class="wrap-input100 validate-input m-b-16" data-validate="Password is required">
                    <input class="input100" type="password" name="spass" placeholder="Store Pass" value="00000">
                </div>

                    <br>
                <div class="container-login100-form-btn m-t-17">
                    <button class="login100-form-btn">
                        ログイン
                    </button>
                </div>


                <a  class="modal-button login1000-form-create-store m-t-25" data-target="modal-reg">
                    店舗アカウントを作成
                </a>
            </form>

            <div id="modal-reg" class="modal">
                <div class="modal-background"></div>
                <div class="modal-card">
                    <header class="modal-card-head">
                        <p class="modal-card-title" align="center"> 店舗アカウントを作成</p>
                        <button class="delete" aria-label="close"></button>
                    </header>

                    <form method='post' action=''>
                        {% csrf_token %}
                        <input type="hidden" name="parking_add" value="parking_add">
                        <section class="modal-card-body">
                            <div class="Location">
                                <label class="label">店舗ID</label>
                                <div class="control">
                                    <input class="input" type="text" name="location">
                                </div>
                            </div>
                            <div class="Classnumber">
                                <label class="label">店舗名称</label>
                                <div class="control">
                                    <input class="input" type="text" name="classnumber">
                                </div>
                            </div>
                            <div class="Location">
                                <label class="label">代表者の名前</label>
                                <div class="control">
                                    <input class="input" type="text" name="location">
                                </div>
                            </div>
                            <div class="Classnumber">
                                <label class="label">住所</label>
                                <div class="control">
                                    <input class="input" type="text" name="classnumber">
                                </div>
                            </div>
                            <div class="Hiragana">
                                <label class="label">グループID</label>
                                <div class="control">
                                    <input class="input" type="text" name="hiragana">
                                </div>
                            </div>
                            <div class="Location">
                                <label class="label">グループパスワード</label>
                                <div class="control">
                                    <input class="input" type="text" name="location">
                                </div>
                            </div>
                        </section>
                        <footer class="modal-card-foot">
                            <!-- <a class="modal-button" data-target="modal-reg2"><button class="button is-info">次へ</button></a> -->
                            <a class="modal-button">
                                <button class="button is-info">登録</button>
                            </a>
                            <a class="modal-button">
                                <button class="button" style="margin-left: 20px;">キャンセル</button>
                            </a>
                        </footer>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'web/bulma/js/clipboard-1.7.1.min.js' %}"></script>
<script src="{% static 'web/bulma/js/main.js' %}"></script>
<script src="{% static 'web/js/jquery.lazyload.min.js' %}"></script>
</body>
</html>